ahoyapi: v2
commands:
  vup:
    cmd: "vagrant up"
    usage: Start the vagrant box if one exists.

  vdown:
    cmd: "vagrant down"
    usage: Stop the vagrant box if one exists.

  ps:
    cmd: docker-compose ps "$@"
    usage: List the running docker-compose containers.

  start:
    cmd: docker-compose start "$@"
    usage: Start the docker-compose containers.

  stop:
    cmd: docker-compose stop "$@"
    usage: Stop the docker-compose containers.

  restart:
    cmd: docker-compose restart "$@"
    usage: Restart the docker-compose containers.

  drush:
    cmd: docker-compose run cli drush --root=docroot "$@"
    usage: Run drush commands in the cli service container.

  bash:
    cmd: docker-compose run "$1" bash
    usage: Start a shell in the container (like ssh without actual ssh).

  sqlc:
    cmd: "docker-compose run cli drush --root=docroot sqlc"
    usage: Connect to the default mysql database. Supports piping of data into the command.

  behat:
    cmd: docker-compose run cli bash -c "cd docroot/test && composer install --prefer-source --no-interaction && bin/behat -p docker $@"
    usage: Run the behat tests within the container.

  behat-init:
    cmd: 'docker-compose run cli bash -c "cd docroot/test && composer install --prefer-source --no-interaction"'
    usage: Use composer to install behat dependencies.

  #This command overrides the up command in the docker.ahoy.yml to test the "last in wins" feature of ahoy
  up:
    cmd: "docker-compose up -d --build"
    usage: Start the docker-compose containers.

  down:
    cmd: "docker-compose down"
    usage: Remove the docker-compose containers.

  logs:
    cmd: "docker-compose logs"
    usage: Docker logs

  build:
    cmd: "docker-compose build"
    usage: Build docker-compose.yml

  composer-install:
    cmd: "composer install"
    usage: Install dependencies


